language: python
python: '2.7'
sudo: required
services:
- docker
branches:
  only:
  - master
  - dev
env:
  global:
  - secure: yDJ+2n6x/04FWzMdgNh59DIA8DrmlzzGRE7HQyHHRM6VCT2cN6pMPSIzlt/YR3thwf0QfcC3ZK+AWe7avucDMovZ3FrtUjpdIkg5rx3DtI7Dv0yNqs4p3wMST6IxxQuC3i2iokfx58T0IpoLDkPbypznNl1tqI+GVSCsq+34OBKCwONZJP9YtYZNjJ4w/TPWoqv9ErqhkSm9sCd9I1PCEdMgw//MKoDrx1a859sCEvDMJa9wbYiKq19n24BQFQIZbRSm+deNpeGRdNLNnvq87zMCS1cbwpvwyG0dnySC5S9EAPTTdLgPdMhG48/2V8GxMEZER01cupTnEwLQ9qc0s9mYmLTQjMVX8rWYgtaqnqUhtFe2XRf7yWZr7zZZ430efMFx/3Y1nazwSk4TFm0NxOd+4ADkccey6tgXtlE7oXt8bfHjbO4/YYsSIjjznUi5cvtWYSrfG9vTx4BZy19jTIpFfmx7BujZpNvjeExERCvBD/iHcoDuv5dxuqHZS8TJRU13guSVznjnEz+dcqzg59XPI3M7EDdD/uWElRE9Cd8YawDbNjkovaDQhmCmVjly4xFmFEGAtBzw2q9p8EW+VYF3RNIWEOeNK7cH+wWmIMsZwyKUv/fwI7l+7vDNO5Y02i5g09wTFeKPmTJLFbRKJvz7b7TTZ3JCpjeRWE0Rt3o=
  - secure: hTNtkhIIeiDp/MK91VtIzGrkKFh/saLU3McU2u/8T7puWaWSrhz3nuaT11M07F18lBpx94BpiWrgEbLLmvFfas816FM+LHJJHuJwGBO5JYTQm6hM1TVVY0+n9np6Fpv42mZ7tzCba1rhG+pbqLXINzJmiKFwBrvf43+Mru3LrLfWu8VLXehqajZ/NRhRLcKNNkpeY27LdKrBFXjzizGkoRR1CyW3atrUaxGH3WtQXgie+2Q1X04ShfVjHqVR1xx/MSU/GY8nrPzI16i8zGvyGx6NBGTD2rzIP3ypTQE2a2sr2oXK0vcQjiO0cNkK9OSAJNg6W9mQzvDEe0TFMFhMj+yS2DBNk3cCJ9aBDezQGmqUysLBrhpzXT2cPIXWB/NgLSHnIAu2+m4UXolYb8gwanIeVZD+E9+RAvXSgVdjdp8PvY+TjwqC3KHJ4+xdIpFKYRR9h5+gp6RykCWps/D8yiUEKHBiUxJ4IqqW7b/wWELBdjFUYgBSlcHk+9cqeuxTEXUF5hJxb7IZM7SgN8lnb1x1jOa/YNFDaS4BQW7YyHagFv9D6KA31zllvi/74vdXvk/4P7cEajXQJASWDlQ7HhNapx/08gTa3xYBm7XfNOmgFtuxrvYF34pHI0SgJoxFixX/6dnV6dedQRQ9Jil0bVkTZRhuj6w3dJShbiwc25Y=
  matrix:
  - VARIANT=onbuild
  - VARIANT=shell
script:
- docker login -u $HUB_USER -p $HUB_PASS
- docker build --no-cache -t $HUB_USER/multipy:$VARIANT -f $VARIANT.Dockerfile .
- docker push $HUB_USER/multipy:$VARIANT
- if [ $VARIANT == "onbuild" ]; then docker tag $HUB_USER/multipy:$TAG $HUB_USER/multipy;
  docker push $HUB_USER/multipy; fi
